# Exercise 1
### Part (a)

- Determinate is 0
- Matrix does not have an inverse
- The rank of the matrix should equal it's size, if not it is singular

In [2]:
#Kaleb Kautzsch
#Part(b)

import scipy as sp
import numpy as np
import numpy.linalg as nla
import scipy.linalg as la

#Matrix A
a = sp.array([[2,4,6,8],
             [-1,0,1,0],
             [1,2,3,4],
             [1,4,7,8]])

#LU decomposition, rank, and null-space
p,l,u = la.lu(a)
rank = nla.matrix_rank(a)
nSpace = la.null_space(a)

print('\nLower Diagonal\n',l,'\n','\nUpper Diagonal\n',u,'\n','\nRank of matrix\n',rank,'\n','\nNull Space is of dimension 2\n',nSpace)


Lower Diagonal
 [[ 1.   0.   0.   0. ]
 [-0.5  1.   0.   0. ]
 [ 0.5  0.   1.   0. ]
 [ 0.5  1.   0.   1. ]] 
 
Upper Diagonal
 [[2. 4. 6. 8.]
 [0. 2. 4. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 
Rank of matrix
 2 
 
Null Space is of dimension 2
 [[-0.55745009 -0.21538861]
 [ 0.54534419 -0.74815946]
 [-0.55745009 -0.21538861]
 [ 0.284778    0.58946834]]


In [3]:
#Part(c)

#Eigenvalues and eigenvectors
eigValues = la.eigvals(a)

print(eigValues,'Eigenvalues of which 2 are equal to zero')

[ 1.25207973e+01+0.j  4.79202711e-01+0.j -1.05487321e-14+0.j
  5.47421787e-17+0.j] Eigenvalues of which 2 are equal to zero


In [4]:
#Part(d)

#SVD on matrix
U, S, Vh = la.svd(a)

print(S,'Singualr Values of which 2 are equal to zero')

[1.67090363e+01 1.67573997e+00 1.80480067e-16 3.80103486e-17] Singualr Values of which 2 are equal to zero


In [5]:
#Part(e)

#Solving Equations
b = sp.array([[12],[0],[6],[12]])
uTrans = U.transpose()
diag = sp.array([[1/S[0],0,0,0],[0,1/S[1],0,0],[0,0,0,0],[0,0,0,0]])
firstDot = sp.dot(Vh.transpose(),diag)
secondDot = sp.dot(uTrans,b)
x = sp.dot(firstDot,secondDot)
check = la.lstsq(a,b)
print('Solution\n',x,'\n','\nCheck to see solution is right\n',check,'\n')

Solution
 [[0.42857143]
 [0.42857143]
 [0.42857143]
 [0.85714286]] 
 
Check to see solution is right
 (array([[0.42857143],
       [0.42857143],
       [0.42857143],
       [0.85714286]]), array([], dtype=float64), 2, array([1.67090363e+01, 1.67573997e+00, 1.80480067e-16, 3.80103486e-17])) 



# Exercise 2

In [6]:
#Kaleb Kautzsch
#Part (a)

a = 1
b = 2
x = 1
y = 1

for k in range(10):
    x,y = y*(a + x**2), b/(a + x**2)
    print(x)
    print(y)

2
1.0
5.0
0.4
10.4
0.07692307692307693
8.396923076923079
0.018321729571271525
1.310156049097899
0.0279687745347386
0.0759774241902131
0.7362390824073594
0.7404890733011719
1.988521124626821
3.0788751163466825
1.291719247766276
13.536535665652755
0.19084931029197522
35.161656645088655
0.010855535745562367


### Part(b)

#### Solve and reorder equations

- Solve for x to get previous answer:
$$x=y(a+x^2)$$

- Solve for b in the second equation:
$$b=y(a+x^2)$$

- Showing this we can say that $$x=b$$ and can substitute it in for b to get a new y equation:
$$y=b/(a+b^2)$$

- Then we can solve for x in this equation to get a new equation for x:

$$x=\sqrt{(b/y)-a)}$$

In [11]:
#Part(b)

a = 1
b = 2
y = 1

for k in range(10):
    x,y = np.sqrt((b/y)-a), b/(a + b**2)
    print(x)
    print(y)

1.0
0.4
2.0
0.4
2.0
0.4
2.0
0.4
2.0
0.4
2.0
0.4
2.0
0.4
2.0
0.4
2.0
0.4
2.0
0.4
