<b>Exercise 1</b> <i>Numerical Stability</i>

In [2]:
#Kaleb Kautzsch Exercise 1
#Import math for calculations
import math
import numpy as np

#Set up variables for calculations
x1 = float(10**-5)
x2 = float(10**-8)

#Now we write the mathematical expressions
cos_x1 = (1-math.cos(x1))/(x1**2)
cos_x2 = (1-math.cos(x2))/(x2**2)

sin_x1 = 2*np.square((math.sin(x1/2))/(x1))
sin_x2 = 2*np.square((math.sin(x2/2))/(x2))

#Compare the values
print("Value for cosin at 10e-5 = " + str("%.18f" % cos_x1) + " and 10e-8 = " + str("%.18f" % cos_x2))
print("Value for sin at 10e-5 = " + str("%.18f" % sin_x1) + " and 10e-8 = " + str("%.18f" % sin_x2))

Value for cosin at 10e-5 = 0.500000041370185389 and 10e-8 = 0.000000000000000000
Value for sin at 10e-5 = 0.499999999995833222 and 10e-8 = 0.500000000000000000


For my values of cos(x) when x = 10e-5 and 10e-8 the values were 0.500000041370185389 for 10e-5 and 0.000000000000000000 for 10e-8 respectively. My values for sin(x) were 0.499999999995833222 for 10e-5 and
0.500000000000000000 for 10e-8.

After doing the lab and realizing that I am good at making typos I fixed some things in the code I had previously. Such as using 10e-5 instead of using 10**-5. After the changes I got much different values with sin(x1) being the most accurate against the true answer in the homework handout. I tried re-arraging the equations to solve for x, but the algebra did not work out for me. I believe there is a better way to do this but I cannot seem to figure it our currently.

<b>Exercise 3</b> <i>LU Decompisition with scipy</i>

In [14]:
#Kaleb Kautzsch Exercise 3
#Import numpy and scipy
import numpy as np
import scipy.linalg as la

#Make an array using numpy
A = np.array([[1, 2, 3],
              [3, 8, 7],
              [2, 0, 7]])

#Designate P, L, U to the transpose of the matrix and print the results
(P, L, U) = la.lu(A)

print(P)

print(L)

print(U)

#Now solve a system of linear equations from matrix A as Ax=b
b = np.array([1, 3, 2])
LU = la.lu_factor(A)

#Solve setting it to the variable x
x = la.lu_solve(LU, b)

print(x)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.125      1.        ]]
[[ 3.          8.          7.        ]
 [ 0.         -5.33333333  2.33333333]
 [ 0.          0.          0.375     ]]
[1.00000000e+00 2.77555756e-17 1.11022302e-16]


I believe the results are different because of machine accuracy and it pivoted where I did not, possibly making it more accurate. The results for the linear equation really blew my mind getting this result: [1.00000000e+00 2.77555756e-17 1.11022302e-16] This shows me how much more accurate a computer can be compared to what I can be for really important things in the future.